### ISSUE TITLE
Dropdown reloads the page

### ISSUE THREAD

**Issue by camdenb** [Abbondanzo/Modern-MyNEU#5]
Not sure if this is a limitation with MyNEU but it'd be neat if the site was a little more SPA-y.

**Comment by camdenb** [comment]
Looks like a CSS-only approach isn't possible.

**Comment by Abbondanzo** [comment]
MyNEU includes this feature by default and the extension is simply a visual change of the button. Removing the functionality MyNEU provides may result in conflicts when a user minimizes/maximizes on a different platform without the extension, thereby preventing the user from displaying that content on a platform with the content. (i.e. Say you minimize on your laptop without the extension, you couldn't maximize on your desktop with the extension if we replace those two buttons).
 
If ITS lets us have a go at actually redesigning the portal, we'd have so much more room for UX/UI improvements that the portal desperately needs. Sadly, hacking over CSS/slight JS improvements is our limitation.
